services:
    n8n:
      image: docker.n8n.io/n8nio/n8n
      container_name: proyecto-n8n
      env_file:
        - ./n8n/.env.n8n
      volumes:
        - n8n_data:/home/node/.n8n
      ports:
        - 5678:5678
      networks:
        - incident-management-net

    postgredb:
      image: postgres:14-alpine
      container_name: incident-management-db
      environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
        - POSTGRES_DB=${POSTGRES_DB}
      volumes:
        - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
        - postgres_data:/var/lib/postgresql/data/
      ports:
        - "5433:5432"
      networks:
        - incident-management-net

    #Rabbitmq configuración
    rabbitmq:
      image: rabbitmq:3-management-alpine
      container_name: incident-management-mq
      volumes:
        - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json
      environment:
        - RABBITMQ_DEFAULT_VHOST=${RABBIT_VHOST}
        - RABBITMQ_DEFAULT_USER=${RABBIT_USER}
        - RABBITMQ_DEFAULT_PASS=${RABBIT_PASSWORD}
        - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=${RABBIT_ADD_ARGS}
      
      ports:
        - "5672:5672"   # Puerto para la comunicación AMQP
        - "15672:15672" # Puerto para la interfaz de gestión web
      networks:
        - incident-management-net

#Declaramos la network que se usa y los volumes
networks:
  incident-management-net:
volumes:
  postgres_data:
  n8n_data: